# Generated by Django 5.0.6 on 2024-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_final', '0002_group_profile_bio_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
